apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-backend:4bc359fbaa59cba6937f98c2a73c469efe8f3ed9
          ports:
            - containerPort: 5000
